workflows:
  build-and-run:
    name: Vote Solver (Free macOS)
    max_build_duration: 60
    triggering:
      events:
        - push
    scripts:
      - echo "🐳 Docker version: $(docker --version)"
      - git clone https://github.com/RanjanLabz/vote-automation.git || echo "Clone failed"
      - ls -la vote-automation/ || echo "No vote-automation dir?"
      - cd vote-automation || exit 1
      - ls -la  # debug: show files
      - test -f run_docker.sh && echo "✅ run_docker.sh exists" || { echo "❌ run_docker.sh MISSING!"; exit 1; }
      - chmod +x run_docker.sh
      - ./run_docker.sh
    artifacts:
      - vote-automation/**/*
      - run_docker.sh
