workflows:
  build-and-run:
    name: Clone repo & run Docker script
    max_build_duration: 120          # minutes
    instance_type: linux_x86_64      # or linux_m2 if you need more power
    triggering:
      events:
        - push
      cancel_previous_builds: true
    environment:
      groups:
        # add any env groups if needed (e.g. secrets)
    scripts:
      - git clone https://github.com/RanjanLabz/vote-automation.git
      - cd vote-automation
      - chmod +x run_docker.sh        # make sure it's executable
      - ./run_docker.sh               # or bash run_docker.sh
    artifacts:
      - vote-automation/**/*          # optional: save files/logs if needed
