workflows:
  version: '2'  # Version should be a string
  build:
    name: Build and Run Docker
    trigger:
      # You can adjust the trigger to define when to start the build
      # For example, on every commit to the 'main' branch
      branches:
        include:
          - main
    jobs:
      - clone_and_run_docker

jobs:
  clone_and_run_docker:
    name: Clone Repo and Run Docker
    docker:
      - image: circleci/python:3.8  # Use an appropriate Docker image for your project
    steps:
      # Step 1: Clone the repository
      - checkout

      # Step 2: Clone the specific repository
      - run:
          name: Clone vote-automation repo
          command: git clone https://github.com/RanjanLabz/vote-automation.git

      # Step 3: Change directory to the cloned repo
      - run:
          name: Change directory to vote-automation
          command: cd vote-automation

      # Step 4: Run the run_docker.sh script
      - run:
          name: Run Docker script
          command: bash run_docker.sh
