version: 2.1

jobs:
  clone_and_run_docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Clone vote-automation repo and execute run_docker.sh
          command: |
            git clone https://github.com/RanjanLabz/vote-automation.git
            cd vote-automation
            # Make script executable in case git didn't preserve permissions
            chmod +x run_docker.sh || true
            bash run_docker.sh   # or ./run_docker.sh

workflows:
  build:
    jobs:
      - clone_and_run_docker
