workflows:
  build-and-run:
    name: Clone repo & run Docker script
    max_build_duration: 120          # minutes (1–120 allowed)
    instance_type: linux             # valid options: linux, linux_x2, linux_x4 (linux_x2 = more powerful/parallel)
    triggering:
      events:
        - push
      cancel_previous_builds: true
    scripts:
      - git clone https://github.com/RanjanLabz/vote-automation.git
      - cd vote-automation
      - chmod +x run_docker.sh       # ensure executable (git sometimes loses +x)
      - ./run_docker.sh              # run it (or bash run_docker.sh)
    artifacts:
      - vote-automation/**/*         # optional: preserve folder / logs / outputs
