version: 2.1

jobs:
  clone_and_run_docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Clone vote-automation and run Docker
          command: |
            git clone https://github.com/RanjanLabz/vote-automation.git
            cd vote-automation
            bash run_docker.sh
      - run:
          name: Wait for solver (optional check)
          command: |
            sleep 10
            curl -f http://localhost:5005/health || echo "No health endpoint"

workflows:
  build:
    jobs:
      - clone_and_run_docker:
          post-steps:
            - store_artifacts:
                path: vote-automation
