version: 2.1

jobs:
  clone_and_run_docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Clone + cd + run script
          command: |
            git clone https://github.com/RanjanLabz/vote-automation.git
            cd vote-automation
            chmod +x run_docker.sh || true
            ./run_docker.sh

workflows:
  build:                        # ← workflow name (no "version" here!)
    jobs:
      - clone_and_run_docker
