workflows:
  build-and-run:
    name: Vote Solver (Free macOS)
    max_build_duration: 60
    triggering:
      events:
        - push
    scripts:
      - 'echo "🐳 Checking Docker: $(docker --version || echo ''Docker not found'')"'
      - 'git clone https://github.com/RanjanLabz/vote-automation.git || echo "Clone failed"'
      - 'ls -la vote-automation/ || echo "Clone dir missing?"'
      - |
        cd vote-automation || exit 1
        ls -la
        if [ -f run_docker.sh ]; then
          echo "✅ run_docker.sh found"
          chmod +x run_docker.sh
          ./run_docker.sh || echo "run_docker.sh exited with code $?"
        else
          echo "❌ run_docker.sh MISSING in $(pwd)"
          ls -la
          exit 1
        fi
    artifacts:
      - vote-automation/**/*
      - "*.log"
