workflows:
  turnstile-solver-auto:
    name: Turnstile Solver - Auto-Cloned Python Run
    max_build_duration: 35                  # Free-plan safe
    triggering:
      events:
        - push                             # Auto-starts on git push
      cancel_previous_builds: true

    scripts:
      - name: Clone the repository
        script: |
          git clone https://github.com/jialezi/turnstile-solver.git
          cd turnstile-solver

      - name: Install Python dependencies
        script: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt || echo "requirements.txt install note"
          pip install playwright quart     # Ensure core packages

      - name: Setup Playwright Chromium
        script: |
          playwright install chromium --with-deps
          playwright --version

      - name: Verify cloned repo contents (debug)
        script: |
          pwd                              # Shows current dir (cloned repo root)
          ls -la                           # Lists app.py, requirements.txt, etc.
          echo "Repo was auto-cloned - no manual git clone needed"

      - name: Launch solver & run quick tests
        script: |
          echo "Starting app.py in background..."
          python3 app.py > solver.log 2>&1 &
          sleep 25                         # Wait for startup

          echo "Health check:"
          curl -s http://127.0.0.1:5000/health || \
          curl -s http://127.0.0.1:5005/health || \
          echo "Health failed - see solver.log"

          echo "Demo Turnstile request:"
          curl -s "http://127.0.0.1:5000/turnstile?url=https://challenges.cloudflare.com&sitekey=0x4AAAAAACU0HhFzKmX2XbPy" || \
          echo "Test request failed"

          echo "Server logs tail:"
          tail -n 30 solver.log || echo "No logs"

    artifacts:
      - solver.log                         # Download after build for full output
